### PR TITLE
Fixes error when there is an empty match at end of string. Closes #789.

### LINKED ISSUE #789: java.lang.ArrayIndexOutOfBoundsException: 32 at StepNameFormatter.java:40 using 4.2.2 version
Moving from 4.1.0 to 4.2.2 for testing 781 I got a different issue on another report

Please refer to attached json and html report.
[Cucumber_HTML_Report.zip](https://github.com/damianszczepanik/cucumber-reporting/files/2603155/Cucumber_HTML_Report.zip)
[SpectrumAnalyzerIT.json.txt](https://github.com/damianszczepanik/cucumber-reporting/files/2612230/SpectrumAnalyzerIT.json.txt)

NOTE: I suggest to improve the report to show what's the affected section of Json file in case of error like this or 781

### PR DESCRIPTION
**Pull request by ekalin**
When there is an empty match at the end of string, such as
@Given("^the card is valid(.*)$")
(with not extra text after "valid), an ArrayIndexOutOfBounds was
generated.

### CODE REVIEW

File: src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java [hunk 1]
```diff
@@ -31,17 +31,29 @@ public static String format(String stepName, Argument[] arguments, String preArg
 
     private static void surroundArguments(Argument[] arguments, String preArgument, String postArgument, String[] chars) {
         for (Argument argument : arguments) {
-            if (argument.getOffset() == null) {
+            if (isNotMatchedArgument(argument)) {
```
Comment (damianszczepanik) [inline src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java]: would rather examine value

File: src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java [hunk 2]
```diff
@@ -31,17 +31,29 @@ public static String format(String stepName, Argument[] arguments, String preArg
...
             chars[end] = chars[end] + postArgument;
         }
     }
 
+    private static boolean isNotMatchedArgument(Argument argument) {
+        return argument.getOffset() == null;
+    }
+
+    private static boolean isArgumentAtEndOfString(int start, String[] chars) {
+        return start >= chars.length;
```
Comment (damianszczepanik) [inline src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java]: what if the val is not empty but should be added at the end of the step?

Comment (ekalin) [reply src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java]: That's testcase format_endsWithArguments.

If the argument is not empty, then the start must be before the end of string.

Comment (damianszczepanik) [inline src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java]: in fact starts = chars.length only if the val is empty :)
