### PR TITLE
Fixes #781: NPE with optional step arguments.

### LINKED ISSUE #781: NullPointerException for optional argument
We have a step like the following:
**@Then("^(\\d+) files(?: matching \"(.*)\")? have been failed to be collected for nodes in file (.*)")**

The second parameter is optional. 
It is managed by correctly Cucumber but when it is not provided we get NullPointerException while generating the report.

**JsonReport when the second parameter is not provided:**
`
           "name": "0 files have been failed to be collected for nodes in file BGF/FileCollectionNodes",
            "match": {
              "arguments": [
                {
                  "val": "0",
                  "offset": 0
                },
                {},
                {
                  "val": "BGF/FileCollectionNodes",
                  "offset": 59
                }
              ],
              "location": "FileCollectionResultNotificationSteps.verifyNumOfFilesToBeCollected(int,String,String)"
            },
`

**LOG:**
`
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'format' in  class net.masterthought.cucumber.util.StepNameFormatter threw exception java.lang.NullPointerException at /templates/macros/json/stepName.vm[line 3, column 47]

....
Caused by: java.lang.NullPointerException
	at net.masterthought.cucumber.util.StepNameFormatter.surroundArguments(StepNameFormatter.java:34)
	at net.masterthought.cucumber.util.StepNameFormatter.format(StepNameFormatter.java:19)
`

**JsonReport when the second parameter is provided:**
`
       "name": "2 files matching \"subscriptionType\u003dBSCRECORDINGS\" have been failed to be collected for nodes in file BSC/StatsFileCollectionNodes",
            "match": {
              "arguments": [
                {
                  "val": "2",
                  "offset": 0
                },
                {
                  "val": "subscriptionType\u003dBSCRECORDINGS",
                  "offset": 18
                },
                {
                  "val": "BSC/StatsFileCollectionNodes",
                  "offset": 101
                }
              ],
              "location": "FileCollectionResultNotificationSteps.verifyNumOfFilesToBeCollected(int,String,String)"
            },
`
     
It seems a regression coming with release 4.2.0

### PR DESCRIPTION
**Pull request by ekalin**
When a step has an optional matching argument and the argument is not
matched, the JSON report has an empty object in place of that argument
in the match array. A check has been added to skip those empty
arguments.

### CODE REVIEW

File: src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java [hunk 1]
```diff
@@ -31,6 +31,10 @@ public static String format(String stepName, Argument[] arguments, String preArg
 
     private static void surroundArguments(Argument[] arguments, String preArgument, String postArgument, String[] chars) {
         for (Argument argument : arguments) {
+            if (argument.getOffset() == null) {
+                continue;
+            }
+
             int start = argument.getOffset();
```
Comment (damianszczepanik) [inline src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java]: move ```start``` above and use it for if condition

Comment (damianszczepanik) [reply src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java]: also can we have this case included into sample.json file?

File: src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java [hunk 2]
```diff
@@ -31,6 +31,10 @@ public static String format(String stepName, Argument[] arguments, String preArg
...
             int end = start + argument.getVal().length() - 1;
```
Comment (damianszczepanik) [inline src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java]: keep start and end together

File: src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java (hunk 1 above)
Comment (ekalin) [reply src/main/java/net/masterthought/cucumber/util/StepNameFormatter.java]: As for moving `start` above, it is possible, but then `start` and `end` would be separated (contrary to what you asked below), because `end` depends on `start` which might be null.
