### PR TITLE
Fix failed report causing net.masterthought.cucumber.ValidationException for Locale TR  #837

### LINKED ISSUE #837: failed report causing net.masterthought.cucumber.ValidationException for Locale TR
## Description
 A failed report causing the following exception for Locale TR;
```
net.masterthought.cucumber.ValidationException: File '/Users/Shared/Jenkins/Home/jobs/myScenario/builds/283/cucumber-html-reports/.cache/cucumber-reports/myJson.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:99)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:71)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:324)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:248)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No enum constant net.masterthought.cucumber.json.support.Status.FAİLED (through reference chain: java.lang.Object[][0]->net.masterthought.cucumber.json.Feature["elements"]->java.lang.Object[][1]->net.masterthought.cucumber.json.Element["steps"]->java.lang.Object[][13]->net.masterthought.cucumber.json.Step["result"]->net.masterthought.cucumber.json.Result["status"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3049)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
	... 14 more
Caused by: java.lang.IllegalArgumentException: No enum constant net.masterthought.cucumber.json.support.Status.FAİLED
	at java.lang.Enum.valueOf(Enum.java:238)
	at net.masterthought.cucumber.json.support.Status.valueOf(Status.java:12)
	at net.masterthought.cucumber.json.deserializers.StatusDeserializer.deserialize(StatusDeserializer.java:28)
	at net.masterthought.cucumber.json.deserializers.StatusDeserializer.deserialize(StatusDeserializer.java:16)
	at net.masterthought.cucumber.json.deserializers.CucumberJsonDeserializer.deserialize(CucumberJsonDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	... 33 more
```

## Exception Stacktrace
https://gist.github.com/dokmetas/5dee5ad12c88fd95bff9fb8c47a069e9

## Environment
CurrentLocale is tr-TR

## Steps to Reproduce
Change default locale to tr-TR and generate report from json which includes FAILED steps.

## RCA
"Failed".upperCase() returns "FAİLED" for tr-TR which causes the exception described above.
More on that below;

"I".toLowerCase() returns "ı" not "i" for tr-TR locale.
"i".toUpperCase() returns "İ" not "I" for tr-TR locale.

### PR DESCRIPTION
**Pull request by dokmetas**
Fix for #837
"Failed".upperCase() returns "FAİLED" for tr-TR which causes the exception described in the issue.
More on that below;

"I".toLowerCase() returns "ı" not "i" for tr-TR locale.
"i".toUpperCase() returns "İ" not "I" for tr-TR locale.

Calling toLowerCase() or toUpperCase() with Locale.US solves the issue.

### CODE REVIEW

File: src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java [hunk 1]
```diff
@@ -2,6 +2,7 @@
```
Comment (damianszczepanik) [inline src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java]: Improve your commit message

File: src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java [hunk 2]
```diff
@@ -25,7 +26,7 @@ public Status deserialize(JsonNode rootNode, Configuration configuration) {
         if (UNKNOWN_STATUSES.contains(status)) {
             return Status.UNDEFINED;
         } else {
-            return Status.valueOf(status.toUpperCase());
+            return Status.valueOf(status.toUpperCase(Locale.US));
```
Comment (damianszczepanik) [inline src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java]: Modify sample.json so there is at least one status for which this fix is applied

File: src/main/java/net/masterthought/cucumber/json/support/Status.java [hunk 3]
```diff
@@ -23,7 +25,7 @@
      * @return status name as lowercase
      */
     public String getRawName() {
-        return name().toLowerCase();
+        return name().toLowerCase(Locale.US);
```
Comment (damianszczepanik) [inline src/main/java/net/masterthought/cucumber/json/support/Status.java]: My suggestion is to take a look at https://github.com/damianszczepanik/cucumber-reporting/tree/master/src/main/java/net/masterthought/cucumber/json/deserializers and move this change insto single class which is executed then the JSON is created instead of having the same fix in many places which are invoked many times during report creation

File: src/test/java/net/masterthought/cucumber/json/deserializers/StatusDeserializerTest.java [hunk 4]
```diff
@@ -26,7 +28,7 @@ public void deserialize_OnDefaultStatus_ReturnsStatus() {
         // given
         Status status = Status.PASSED;
         JsonNode node = mock(JsonNode.class);
-        when(node.asText()).thenReturn(status.name().toLowerCase());
+        when(node.asText()).thenReturn(status.name().toLowerCase(Locale.US));
 
         StatusDeserializer deserializer = new StatusDeserializer();
```
Comment (damianszczepanik) [inline src/test/java/net/masterthought/cucumber/json/deserializers/StatusDeserializerTest.java]: and the unit test for new code

File: src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java (hunk 2 above)
Comment (dokmetas) [reply src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java]: sample.json already have entries with "status":"failed" so no change is necessary at the moment.

File: src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java [hunk 5]
```diff
@@ -21,6 +22,7 @@
     @Override
     public Status deserialize(JsonNode rootNode, Configuration configuration) {
 
+        Locale.setDefault(Locale.US);
```
Comment (damianszczepanik) [inline src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java]: Best would be to restore previous locale once below code is completed

**Comment by damianszczepanik** [comment]
Thanks for contribution

File: src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java (hunk 5 above)
Comment (dokmetas) [reply src/main/java/net/masterthought/cucumber/json/deserializers/StatusDeserializer.java]: hi @damianszczepanik 
After spending some time on this, I believe the best way to restore previous locale is to pass Locale.ENGLISH parameter in the firstplace for each method that are used for status strings that are intended to be interpreted locale independently, such as PASSED, FAILED etc (These are English words anyway) rather than changing default locale.

No args toUpperCase() returns toUpperCase(Locale.getDefault()) so there is no difference between calling "toUpperCase() which in turn calls toUpperCase(Locale.getDefault())" and "toUpperCase(Locale.ENGLISH)"

Let me know what your opinion is and I can make necessary updates. I already identified two files that would require changes.
This is the same approach as my first commit for this pull request but updating only bare minimum files this time.
